### ISSUE TITLE
The name test of kedem.

### ISSUE THREAD

**Issue by mldk-tech** [Gizra/kedem-shoov-visual#6]
The name of Kedem test, from the list of Gizra, differs from the name test inside the breadcrumbs in a page of Kedem.

list of Gizra
![kedemshoovvisual](https://cloud.githubusercontent.com/assets/5812423/11322794/452af716-9105-11e5-886a-3e21736355a4.png)

Breadcrumbs in a page of Kedem.
![kedemshoov](https://cloud.githubusercontent.com/assets/5812423/11322797/527a93fe-9105-11e5-9427-d438c3273231.png)

**Comment by amitaibu** [comment]
Repo is public, so I removed to list of projects image.

One is the node title, and the other is the name from GitHub. We still don't sync it, but for now I'll close under "by design"
