### ISSUE TITLE
Errors messages from the visual monitor system

### ISSUE THREAD

**Issue by mldk-tech** [Gizra/kedem-shoov-visual#8]
At that time there were errors in the system, [kedem](https://app.shoov.io/#/repos/18202)

![selection_003](https://cloud.githubusercontent.com/assets/5812423/11360794/4e4341aa-9290-11e5-91f6-c6220c98ac73.png)

We have it in other projects like [cbn](https://app.shoov.io/#/repos/6101)

![selection_004](https://cloud.githubusercontent.com/assets/5812423/11360842/b6be6e26-9290-11e5-9939-c0f010c7ff20.png)

and [icenter](https://app.shoov.io/#/repos/14784)

![selection_005](https://cloud.githubusercontent.com/assets/5812423/11360955/e23a7a58-9291-11e5-81e6-6cc92b21916c.png)

These errors do not indicate visual problems

**Comment by mldk-tech** [comment]
From the last minutes

kedem
![selection_008](https://cloud.githubusercontent.com/assets/5812423/11362172/b1c3cdb2-929a-11e5-97f5-0c6227bc533a.png)

cbn
![selection_007](https://cloud.githubusercontent.com/assets/5812423/11362111/63e2a866-929a-11e5-91ad-72f05b84bfd4.png)

icenter
![selection_006](https://cloud.githubusercontent.com/assets/5812423/11362064/1a512e84-929a-11e5-951c-6e772b3df6cd.png)

**Comment by amitaibu** [comment]
Please add the errors you see not just the ID of the build errors.

**Comment by mldk-tech** [comment]
I thought you would be more comfortable to get into the links and see the errors.
But no problem I'll add the errors within the id's.

For all the projects:
An unknown server-side error occurred while processing the command.
![selection_009](https://cloud.githubusercontent.com/assets/5812423/11365645/68ed2a96-92b0-11e5-938b-45aa0a171c8d.png)

**Comment by DavidKohav** [comment]
Kedem
An unknown server-side error occurred while processing the command.
![selection_009](https://cloud.githubusercontent.com/assets/5812423/11365645/68ed2a96-92b0-11e5-938b-45aa0a171c8d.png)

**Comment by amitaibu** [comment]
Indeed, the answer to the bug is written in the screenshot. Reached the
quota in browserstack
