### ISSUE TITLE
Home page design

### ISSUE THREAD

**Issue by mldk-tech** [Gizra/kedem-shoov-visual#9]
This is the right design?

http://test-kedem.gotpantheon.com
![selection_013](https://cloud.githubusercontent.com/assets/5812423/11612266/a0a3225c-9bfb-11e5-87cb-024016d4d172.png)

**Comment by bitamar** [comment]
It is. We just need to remove the mailchimp subscription error message.

**Comment by mldk-tech** [comment]
let me know when it's happen, 10x
